In [1]:
import numpy as np

In [3]:
list = [1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [4]:
print('1D Array')
a = np.array([1, 2, 3, 4, 5])
print(a)

print('2D Array')
b = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10]])
print(b)

print('3D Array')
c = np.array([[[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10], 
              [11, 12, 13, 14, 15]]])
print(c)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [5]:
type(a)

numpy.ndarray

In [6]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [7]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [8]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [9]:
d = np.array([[1, 2, 3, 4.2, 5], 
              [6, 7, 8.9, 9, 10], 
              [11, 12, 13, 14, 15]])

print(d.dtype)

float64


In [10]:
d.transpose()

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8.9, 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

In [11]:
np.empty((4,4), dtype = float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.45599366e-307],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [12]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [13]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [16]:
y = np.zeros((4,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
z = np.zeros((4,8), dtype = int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
z = np.zeros((4,8), dtype = str)
z

array([['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '']], dtype='<U1')

In [20]:
z = np.zeros((4,8), dtype = bool)
z

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [21]:
a = np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
a = np.arange(1,20, 2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [23]:
a = np.arange(2,20, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [24]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [25]:
b = np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
b = b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [27]:
b = b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [28]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [30]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [31]:
a[0]

array([1, 2, 3, 4, 5])

In [32]:
a[2]

array([11, 12, 13, 14, 15])

In [33]:
a[0,0]

1

In [34]:
a[3,4]

20

In [35]:
a[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [37]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [38]:
a[2:5,4]

array([15, 20, 25])

In [39]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [40]:
a[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [41]:
a[:, 2:5].dtype

dtype('int32')

In [42]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20, 38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [43]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [44]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [45]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [46]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [47]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [48]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [49]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [50]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [52]:
print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [53]:
b = b.reshape((3,6))

In [54]:
print(a.shape)
print(b.shape)

(6, 3)
(3, 6)


In [55]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [56]:
b.max()

37

In [57]:
b.min()

20

In [58]:
b.argmax()

17

In [59]:
np.sum(b)

513

In [60]:
np.sum(b, axis = 1)

array([135, 171, 207])

In [61]:
np.sum(b, axis = 0)

array([78, 81, 84, 87, 90, 93])

In [62]:
np.mean(b)

28.5

In [63]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [64]:
np.std(b)

5.188127472091127

In [65]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])

In [66]:
np.random.random(1)

array([0.75369209])

In [67]:
np.random.random(2)

array([0.68349943, 0.0455106 ])

In [68]:
np.random.random((2,2))

array([[0.55569596, 0.9374229 ],
       [0.14668779, 0.07662783]])

In [69]:
np.random.randint(1,10)

3

In [70]:
np.random.randint(1,10, (2,2))

array([[1, 8],
       [8, 9]])

In [71]:
np.random.randint(1,10, (3,4,5))

array([[[1, 5, 6, 5, 1],
        [7, 4, 3, 2, 8],
        [4, 3, 9, 3, 9],
        [1, 7, 8, 5, 2]],

       [[2, 5, 2, 4, 1],
        [5, 5, 5, 8, 7],
        [4, 8, 7, 9, 3],
        [7, 5, 4, 9, 1]],

       [[3, 1, 7, 3, 5],
        [3, 1, 8, 1, 5],
        [4, 2, 8, 1, 3],
        [2, 7, 9, 9, 6]]])

In [72]:
np.random.rand(2,2)

array([[0.97772871, 0.71393612],
       [0.0827008 , 0.84906447]])

In [73]:
np.random.randn(2,2)

array([[-0.85391934,  1.79839212],
       [-1.2776626 , -0.57960838]])

In [74]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [75]:
np.random.choice(a)

8

In [80]:
s1 = "Hello I'm Richie"
s2 = "Do watch Chandrayaan 3 moon landing tomorrow."

In [81]:
np.char.add(s1, s2)

array("Hello I'm RichieDo watch Chandrayaan 3 moon landing tomorrow.",
      dtype='<U61')

In [82]:
np.char.upper(s1)

array("HELLO I'M RICHIE", dtype='<U16')

In [83]:
np.char.lower(s1)

array("hello i'm richie", dtype='<U16')

In [84]:
np.char.split(s1)

array(list(['Hello', "I'm", 'Richie']), dtype=object)

In [85]:
s3 = 'Corvette is a\nmuscle car'
np.char.splitlines(s3)

array(list(['Corvette is a', 'muscle car']), dtype=object)

In [86]:
np.char.replace(s1, 'name', 'sirname')

array("Hello I'm Richie", dtype='<U16')

In [87]:
print('**********good bye***********')

**********good bye***********


In [88]:
print(np.char.center('good bye', 80, '*'))

************************************good bye************************************
